import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"]
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

interface RootLayoutProps {
	children: React.ReactNode;
	"rick-and-morty": React.ReactNode;
	"star-wars": React.ReactNode;
}

export default function RootLayout(props: Readonly<RootLayoutProps>) {
	const slots = ["children", "rick-and-morty-server", "rick-and-morty-client", "rick-and-morty-client-with-action"];

	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<div
					style={{
						display: "grid",
						gridTemplateColumns: "repeat(auto-fit, minmax(40vw, 1fr))",
						gap: "1rem",
						padding: "1rem"
					}}
				>
					{slots.map((slot, i) => (
						<div
							key={i}
							style={{
								maxHeight: "calc(50vh - 2rem)",
								overflow: "auto",
								border: "1px solid #444",
								padding: "1rem",
								borderRadius: "0.5rem"
							}}
						>
							{props[slot as keyof typeof props]}
						</div>
					))}
				</div>
			</body>
		</html>
	);
}
